[versions]
spring-boot = "3.2.5"
firebase-admin = "9.2.0"
lombok = "1.18.30"
mapstruct = "1.6.0"
lombok-mapstruct-binding = "0.2.0"

[libraries]
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebase-admin" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lombok-mapstruct-binding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
